# Generated by Django 3.1.4 on 2021-02-13 13:56

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sw_oneone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uId', models.IntegerField()),
                ('workedQuestion', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_past_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='number_of_question',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='number_of_times',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
